# These are supported funding model platforms

# GitHub Sponsors (primary)
github: kareem2099

# Alternative platforms
patreon: # Add Patreon username
open_collective: # Add Open Collective username
ko_fi: freerave # Ko-fi profile for the developer
tidelift: # Only for commercial dependencies
community_bridge: # Community Bridge project-name
liberapay: # Liberapay username
issuehunt: # Add IssueHunt username
otechie: # Add Otechie username

# Custom donation links (PayPal, Buy Me a Coffee, etc.)
custom: [
  "https://paypal.me/freerave1",
  "https://buymeacoffee.com/freerave"
]
